@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Car",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1217114922 { 
   	label=EconomyCar
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   EconomyCar1217114922[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EconomyCar</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   priceStrategy: PriceStrategy [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calculatePrice(days: int): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_227162853 { 
   	label=PremiumPriceStrategy
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   PremiumPriceStrategy227162853[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PremiumPriceStrategy</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calculatePrice(days: int): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_365845503 { 
   	label=StandardPriceStrategy
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   StandardPriceStrategy365845503[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StandardPriceStrategy</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calculatePrice(days: int): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_407616871 { 
   	label=LuxuryCar
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   LuxuryCar407616871[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LuxuryCar</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   priceStrategy: PriceStrategy [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calculatePrice(days: int): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_67508 { 
   	label=Car
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Car67508[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Car</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ calculatePrice(days: int): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDescription(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ setPriceStrategy(strategy: PriceStrategy)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 

'edges    
Car67508 -> EconomyCar1217114922[arrowhead=none, arrowtail=empty, dir=both];
Car67508 -> LuxuryCar407616871[arrowhead=none, arrowtail=empty, dir=both];
LuxuryCar407616871 -> PremiumPriceStrategy227162853[arrowhead=none];
LuxuryCar407616871 -> StandardPriceStrategy365845503[arrowhead=none];
    
}
@enduml